### ISSUE TITLE
段位、选人规则改革方案

### ISSUE THREAD

**Issue by rolevax** [rolevax/ih#11]
1. 开桌后选人改为预约前完全自由选人
2. 角色无重复的四人预约后即开始一桌
3. 终局pt与R值不再根据顺位变动，而是参照“同阵容得点排行”（下面有说明）
4. 段位不再是每个帐号一个，而是对每个帐号的每个少女分别记录
5. 弃用应援、替补、正选、ACE的分级，pt一律按正选规则变动

什么是“同阵容得点排行”
- 以三个京狗为对手拿一位的照姐，和以三个照姐为对手拿三位的京狗，虽然前者顺位更高，但后者更有水平。对于不同阵容下产生的结果，相互比较是毫无意义的。段位作为水平的指标，应当以公平条件下的对比结果为基准。
- 因此，我们不再采用一局比赛表面上的顺位决定pt变动，而是用“同样的阵容，如果换了别的玩家打会怎么样”这种思路来评判高低。
- 为了进行这种公平比较，我们需要对每一种阵容组合，记录过去玩家的历史成绩，形成排行。即“全服所有人用同样的少女，和同样的对手对局，终局得点之排行”
- 当一局结束后，pt变动的基准由同阵容排行决定。排入上位25%如同吃一，排入准上位25%如同吃二，准下位25%如同吃三，下位25%如同吃四
- 例如，自己用咲，对手是衣、勇者、猫；一局打完后得了23300点。这个时候，系统会捞出过去所有的以“咲x衣x勇者x猫”这个阵容进行的对局记录，看看别人在这个阵容下用咲得了多少点，并查出这次的23300点在其中排第几。假如同阵容记录共有100条，而这次的233000点在其中排了第30名，也就是准上位25%，那么这次的结果判定就如同吃二（无论这次比赛的实际顺位是多少），在正选规则下就是+30pt。

**Comment by kurokuro35** [comment]
其实 可以考虑moba游戏设置给高端段位设置ban/pick 一人选出一个最不想遇到的ban掉 然后再开始选人

**Comment by rolevax** [comment]
@kurokuro35 这么做的优点是什么？

**Comment by I-sakisan** [comment]
将段位划分到（账号，角色）级别：这是很好的举措，非常赞同

自由选人：大家都能选择自己喜爱的少女，本来是一件好事，但是给定一个少女团体（set）后，选择其中强度与游戏性兼备的最好的一批少女的比例我想会很高（以目前已出少女范围为例，大概是慕、怜、杏果、夕这些），反反复复只有那么几组对阵可能无趣。我觉得现在的先随机给范围，玩家在范围中自主选择的机制已经很好了，尽量做到了减少只能玩不喜欢角色的频率的同时又能维持对阵角色组合的大量变化。如果让我设想选人机制，估计会在现有基础上改为在选人画面只能看到自己的选人范围（对，就和三国杀选武将差不多）

“同阵容得点排行”：这是要从规则上把顺位战改成点数战了，我并不认同。慕曾经说“有分差的话就根据分差，要考虑的事情也都不一样”，注意到少女们所参加大赛的规则，可以看到天麻世界里的麻将也是争顺位为主，因此我认为段位的变动还是应当以当场的顺位为依据更佳

取消段位战区划分：我觉得不必。。。虽然不能阻止高玩屠幼，但防止萌新误闯boss战还是有其意义的吧

**Comment by rolevax** [comment]
@I-sakisan 

新段位制背后的思路是这样的：

- 一场比赛的结果由三个因素决定：外挂、技术、运气
- 其中运气是辣油的固有特性，不管了；那么剩下的就是外挂和技术
- 在二次元中，外挂和技术都是可比较的维度。无论是因为挂不如人还是因为技不如人，输掉都不冤
- 但在三次元中，只有技术是可比较的。如果因为挂不如人而输掉，玩家会觉得这是系统机制的错
- 目前看来，如果单看表面顺位，外挂的影响是决定性的，技术的作用不大。依据是后面给出的统计数据
- 换句话讲，一场比赛表面上的顺位与其说是玩家间的顺位，不如说是角色间的顺位

统计数据：（其中1位率54.52%的那个是淡，1位率9.67%那个是茶杯）
```
+---------+--------+--------+--------+--------+
| girl_id | r1     | r2     | r3     | r4     |
+---------+--------+--------+--------+--------+
|  710115 | 0.5452 | 0.2466 | 0.1007 | 0.1075 |
|  990002 | 0.3084 | 0.3031 | 0.2106 | 0.1780 |
|  712714 | 0.3012 | 0.1880 | 0.2356 | 0.2752 |
|  712411 | 0.2994 | 0.2216 | 0.1903 | 0.2887 |
|  713311 | 0.2690 | 0.2599 | 0.2386 | 0.2325 |
|  710114 | 0.2608 | 0.2791 | 0.2231 | 0.2370 |
|  715212 | 0.2543 | 0.2666 | 0.2616 | 0.2174 |
|  712412 | 0.2519 | 0.2604 | 0.2492 | 0.2385 |
|  713815 | 0.2441 | 0.2360 | 0.2486 | 0.2712 |
|  990001 | 0.2434 | 0.2287 | 0.2658 | 0.2620 |
|  714915 | 0.2421 | 0.2123 | 0.2559 | 0.2897 |
|  712613 | 0.2351 | 0.2726 | 0.2559 | 0.2364 |
|  712611 | 0.2319 | 0.2927 | 0.2972 | 0.1782 |
|  712715 | 0.2265 | 0.2417 | 0.3220 | 0.2098 |
|  713314 | 0.2249 | 0.2990 | 0.2436 | 0.2325 |
|  713301 | 0.2237 | 0.2355 | 0.2771 | 0.2637 |
|  990003 | 0.2031 | 0.2109 | 0.2871 | 0.2988 |
|  712413 | 0.1656 | 0.2533 | 0.2896 | 0.2914 |
|  712915 | 0.1559 | 0.2586 | 0.2817 | 0.3038 |
|  713811 | 0.1391 | 0.2355 | 0.3055 | 0.3200 |
|  710113 | 0.0967 | 0.2081 | 0.2962 | 0.3990 |
+---------+--------+--------+--------+--------+
```
现在具有鸭倒性差距的角色一共就那几个，但以后角色多了这种鸭倒的现象估计会越来越严重

---

以上是“问题”。为了解决这个问题，我搞了个“同阵容得点排名”——这个解法是有毛病，比如弱化了“顺位战”的气息，计算量大，部分人群理解困难等等。也在想其它的办法。

**Comment by rolevax** [comment]
选人规则和pt升降基准其实是二位一体的。一旦奖惩规则和角色自身的强弱脱离关系，选角色基本上就看个人的喜好了——天麻角色的人气分布比较均匀，问题应该不大。就算有明显的倾向性，也可以靠任务/成就/活动之类的东西来弥补。

取消战区划分主要还是因为人少，分不起。小众性是这个平台的特色，将来所有的设计都会以小众性为前提，设计的结果也会和主流的大众向产品有一些区别。

**Comment by I-sakisan** [comment]
既然如此，我就对这个改革案提出一些小修小补的意见吧。
首先是同阵容得点排名，这个点数可以不采用纯粹的点棒数，而是加上顺位点作为修正。
然后就是划分战区的问题，如果场上总是存在一个宫永照或者天江衣，对于一些挂力稍弱的角色厨来说就很尴尬了。合宿时池田大牌狂扫兴奋不已，但如果上了藤田兔子魔王那桌，恐怕不到接近被婊哭的状态也很难做什么，玩着就没多大意思了，当然或许这是我由于不想（shi）找（dou）虐（m）而单方面的想法吧。根本目的是尽量减少单方面屠杀式的角色组合，而划分战区是我能想到的比较简明又有效的办法（楼上的ban角色会使高人气强力魔物基本必ban，也对吸引玩家不利）
既然现在一个用户账号对应着一批（用户，角色）子账号，对这些子账号分战区应当不至于分不起。如果怕萌新在应援区无法匹配到对手，那么允许用户注册时填写初始等级（开放到1级完全可行，但考虑到R最好不要膨胀，初始号能否上正选可能需要考量一下）就好。
